### ISSUE TITLE
Add SQL Reference doc page for dedup unique ID feature for insert batches

### ISSUE THREAD

**Issue by e-mars** [ClickHouse/clickhouse-docs#121]
based on release 22.2.X
https://clickhouse.com/docs/en/whats-new/changelog/#:~:text=Add%20a%20setting,Igor%20Nikonov

**Comment by DanRoscigno** [comment]
Add a setting that allows a user to provide own deduplication semantic in MergeTree/ReplicatedMergeTree If provided, it's used instead of data digest to generate block ID. So, for example, by providing a unique value for the setting in each INSERT statement, the user can avoid the same inserted data being deduplicated. This closes: [#7461](https://github.com/ClickHouse/ClickHouse/issues/7461). [#32304](https://github.com/ClickHouse/ClickHouse/pull/32304) ([Igor Nikonov](https://github.com/devcrafter)).

**Comment by DanRoscigno** [comment]
closed by https://clickhouse.com/docs/en/operations/settings/settings/#insert_deduplication_token
