### ISSUE TITLE
Unable to grab data from `[...] publicdata.landregistry.gov.uk [...]` in Quickstart

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1452]
Under [Step 7 in the Quickstart](https://clickhouse.com/docs/en/getting-started/quick-start#7-insert-your-own-data) the reader can select the **Web** tab to attempt to download some land registry data:

```sql
SELECT *
FROM url(
    'http://prod2.publicdata.landregistry.gov.uk.s3-website-eu-west-1.amazonaws.com/pp-complete.csv',
    'CSV'
  );
```

I ran into the following error:

```plaintext
...

Received exception from server (version 23.8.1):
Code: 483. DB::Exception: Received from localhost:9000. DB::Exception: Too many redirects while trying to access http://prod2.publicdata.landregistry.gov.uk.s3-website-eu-west-1.amazonaws.com/pp-complete.csv: Cannot extract table structure from CSV format file. You can specify the structure manually. (TOO_MANY_REDIRECTS)
```

I tried this on both Windows (using Ubuntu in WSL 2) and MacOS Ventura. There's a very real chance that there's something up with my network, so it makes sense for someone to run the above command to validate what's going on 😅 .

**Comment by alexey-milovidov** [comment]
Thank you for the finding!
The docs are fixed in https://github.com/ClickHouse/clickhouse-docs/pull/1460

Why does it argue about redirects?
1. The server does a redirect.
2. ClickHouse has a setting `max_http_get_redirects`, which is set to zero by default, which means "don't allow redirects".
3. It does not allow redirects by default to protect from SSRF attacks.
4. SSRF attack is the case when an external server redirects to another address, but that address appears to be internal to the company's infrastructure, and by sending an HTTP request to an internal server, you could request an internal API from the internal network, bypassing the auth.
5. When you don't have an internal infrastructure (including something running on your localhost), or you trust the server, it is safe to allow redirects.
6. Although in this particular case, the URL uses HTTP instead of HTTPS, and you will have to trust not only the remote server but also your ISP and every network in the middle.

**Comment by johnnymatthews** [comment]
Oh nice! Thanks for the explanation! I just tried the updated command in #1460 and it works.
