### ISSUE TITLE
Duplicate installation guide.

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/clickhouse-docs#1790]
https://clickhouse.com/docs/en/architecture/single-node-deployment has a section on installing ClickHouse. Let's remove that and instead point to the [official install guide](https://clickhouse.com/docs/en/install).

**Comment by johnnymatthews** [comment]
[This page](https://clickhouse.com/docs/en/architecture/single-node-deployment) doesn't actually mention deployment at all -- it's simply telling the reader how to install ClickHouse locally using a `deb` package, and import some sample data. Since this information already exists in other places in the docs, I recommend we delete this page and add redirect.

Thoughts @rschu1ze?

**Comment by rschu1ze** [comment]
Agree, the [page](https://clickhouse.com/docs/en/architecture/single-node-deployment) merely duplicates 
- the anonymized web analytics dataset ([here](https://clickhouse.com/docs/en/getting-started/example-datasets/metrica)) and
- the official install guide ([here](https://clickhouse.com/docs/en/install)).

Let's do as you propose.

(perhaps we don't even need a redirect but that's up to you)

**Comment by johnnymatthews** [comment]
Addressed in https://github.com/ClickHouse/clickhouse-docs/pull/1825. I added the redirect in there, just in case there's any external links pointing to this (now deleted) page.
