### ISSUE TITLE
Document `anova` function.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1932]
Create documentation for the `anova` function. See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@nikitamikhaylov I'm working on this issue and saw that you are the creator of this function. I'm trying to come up with a simple real world example for the function documentation rather than just using `SELECT analysisOfVariance(number, number % 2) FROM numbers(10)` from the tests. 

If we have some (probably fictional) data for blood pressure readings of patients after treatment by one of three different groups of medicines:

```
patient_id,blood_pressure,medicine_type
1,128,0
2,130,0
3,132,0
4,135,0
5,129,0
6,130,0
7,131,0
8,133,0
9,134,0
10,136,0
11,138,0
12,131,0
13,133,0
14,132,0
15,135,0
16,136,0
17,139,0
18,137,0
19,130,0
20,132,0
21,134,0
22,136,0
23,129,0
24,131,0
25,133,0
26,135,0
27,137,0
28,136,0
29,134,0
30,132,0
31,131,1
32,133,1
33,135,1
34,138,1
35,140,1
36,132,1
37,134,1
38,136,1
39,139,1
40,141,1
41,144,1
42,135,1
43,137,1
44,138,1
45,141,1
46,142,1
47,145,1
48,137,1
49,139,1
50,140,1
51,143,1
52,144,1
53,135,1
54,137,1
55,139,1
56,142,1
57,145,1
58,144,1
59,143,1
60,142,1
61,130,2
62,132,2
63,134,2
64,137,2
65,139,2
66,131,2
67,133,2
68,136,2
69,139,2
70,142,2
71,145,2
72,133,2
73,135,2
74,137,2
75,139,2
76,140,2
77,143,2
78,134,2
79,136,2
80,138,2
81,140,2
82,141,2
83,132,2
84,134,2
85,136,2
86,139,2
87,141,2
88,140,2
89,138,2
90,136,2
```

```sql
CREATE TABLE tab (patient_id UInt8, blood_pressure UInt8, medicine_type UInt8) ENGINE=MergeTree() ORDER BY patient_id;
INSERT INTO tab (*) SELECT FROM file('datatab.csv');
SELECT anova(blood_pressure, medicine_type) FROM tab;
```

Returns 

```
┌─anova(blood_pressure, medicine_type)────┐
│ (20.17205240175227,6.34611212468883e-8) │
└─────────────────────────────────────────┘

```
Is this a correct usage of this function? I see from the implementation that it returns an f-value and a p-value but values seem pretty extreme in my usage so I think I am doing something wrong. Or maybe it's just not good data to use - my knowledge of statistics at this point is rather rusty sadly.
