### ISSUE TITLE
Document `toXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2022]
Create documentation for the `toXYZ` functions. See #1833 for details on how to complete this issue.

- [ ] toBool
- [ ] toDateTime64OrDefault
- [ ] toDateTime64OrNull
- [ ] toDateTime64OrZero
- [ ] toDecimal128
- [ ] toDecimal128OrDefault
- [ ] toDecimal128OrNull
- [ ] toDecimal128OrZero
- [ ] toDecimal256
- [ ] toDecimal256OrDefault
- [ ] toDecimal256OrNull
- [ ] toDecimal256OrZero
- [ ] toDecimal32
- [ ] toDecimal32OrDefault
- [ ] toDecimal32OrNull
- [ ] toDecimal32OrZero
- [ ] toDecimal64
- [ ] toDecimal64OrDefault
- [ ] toDecimal64OrNull
- [ ] toDecimal64OrZero
- [ ] toDecimalString
- [ ] toFixedString
- [ ] toFloat32
- [ ] toFloat32OrDefault
- [ ] toFloat32OrNull
- [ ] toFloat32OrZero
- [ ] toFloat64
- [ ] toFloat64OrDefault
- [ ] toFloat64OrNull
- [ ] toFloat64OrZero
- [ ] toIPv4OrDefault
- [ ] toIPv4OrNull
- [ ] toIPv4OrZero
- [ ] toIPv6OrDefault
- [ ] toIPv6OrNull
- [ ] toIPv6OrZero
- [ ] toISOWeek
- [ ] toISOYear
- [ ] toInt128
- [ ] toInt128OrDefault
- [ ] toInt128OrNull
- [ ] toInt128OrZero
- [ ] toInt16
- [ ] toInt16OrDefault
- [ ] toInt16OrNull
- [ ] toInt16OrZero
- [ ] toInt256
- [ ] toInt256OrDefault
- [ ] toInt256OrNull
- [ ] toInt256OrZero
- [ ] toInt32
- [ ] toInt32OrDefault
- [ ] toInt32OrNull
- [ ] toInt32OrZero
- [ ] toInt64
- [ ] toInt64OrDefault
- [ ] toInt64OrNull
- [ ] toInt64OrZero
- [ ] toInt8
- [ ] toInt8OrDefault
- [ ] toInt8OrNull
- [ ] toInt8OrZero
- [ ] toIntervalDay
- [ ] toIntervalHour
- [ ] toIntervalMicrosecond
- [ ] toIntervalMillisecond
- [ ] toIntervalMinute
- [ ] toIntervalMonth
- [ ] toIntervalNanosecond
- [ ] toIntervalQuarter
- [ ] toIntervalSecond
- [ ] toIntervalWeek
- [ ] toIntervalYear
- [ ] toRelativeDayNum
- [ ] toRelativeHourNum
- [ ] toRelativeMinuteNum
- [ ] toRelativeMonthNum
- [ ] toRelativeQuarterNum
- [ ] toRelativeSecondNum
- [ ] toRelativeWeekNum
- [ ] toRelativeYearNum
- [ ] toStartOfMicrosecond
- [ ] toStartOfMillisecond
- [ ] toStartOfNanosecond
- [ ] toTime
- [ ] toTimezone
- [ ] toTypeName
- [ ] toUInt128
- [ ] toUInt128OrNull
- [ ] toUInt128OrZero
- [ ] toUInt16
- [ ] toUInt16OrDefault
- [ ] toUInt16OrNull
- [ ] toUInt16OrZero
- [ ] toUInt256
- [ ] toUInt256OrDefault
- [ ] toUInt256OrNull
- [ ] toUInt256OrZero
- [ ] toUInt32
- [ ] toUInt32OrDefault
- [ ] toUInt32OrNull
- [ ] toUInt32OrZero
- [ ] toUInt64
- [ ] toUInt64OrDefault
- [ ] toUInt64OrNull
- [ ] toUInt64OrZero
- [ ] toUInt8
- [ ] toUInt8OrDefault
- [ ] toUInt8OrNull
- [ ] toUInt8OrZero
- [ ] toUnixTimestamp64Micro
- [ ] toUnixTimestamp64Milli

Child issue of #1833.

**Comment by Blargian** [comment]
- [ ] toBool
- [ ]  toDateTime64OrDefault
- [ ]  toDateTime64OrNull
- [ ]  toDateTime64OrZero
- [ ]  toDecimal128
- [ ]  toDecimal128OrDefault
- [ ]  toDecimal128OrNull
- [ ]  toDecimal128OrZero
- [ ]  toDecimal256
- [ ]  toDecimal256OrDefault
- [ ]  toDecimal256OrNull
- [ ]  toDecimal256OrZero
- [ ]  toDecimal32
- [ ]  toDecimal32OrDefault
- [ ]  toDecimal32OrNull
- [ ]  toDecimal32OrZero
- [ ]  toDecimal64
- [ ]  toDecimal64OrDefault
- [ ]  toDecimal64OrNull
- [ ]  toDecimal64OrZero
- [ ]  toDecimalString
- [ ]  toFixedString
- [ ]  toFloat32
- [ ]  toFloat32OrDefault
- [ ]  toFloat32OrNull
- [ ]  toFloat32OrZero
- [ ]  toFloat64
- [ ]  toFloat64OrDefault
- [ ]  toFloat64OrNull
- [ ]  toFloat64OrZero
- [ ]  toIPv4OrDefault
- [ ]  toIPv4OrNull
- [ ]  toIPv4OrZero
- [ ]  toIPv6OrDefault
- [ ]  toIPv6OrNull
- [ ]  toIPv6OrZero
- [ ]  toISOWeek
- [ ]  toISOYear
- [ ]  toInt128
- [ ]  toInt128OrDefault
- [ ]  toInt128OrNull
- [ ]  toInt128OrZero
- [ ]  toInt16
- [ ]  toInt16OrDefault
- [ ]  toInt16OrNull
- [ ]  toInt16OrZero
- [ ]  toInt256
- [ ]  toInt256OrDefault
- [ ]  toInt256OrNull
- [ ]  toInt256OrZero
- [ ]  toInt32
- [ ]  toInt32OrDefault
- [ ]  toInt32OrNull
- [ ]  toInt32OrZero
- [ ]  toInt64
- [ ]  toInt64OrDefault
- [ ]  toInt64OrNull
- [ ]  toInt64OrZero
- [ ]  toInt8
- [ ]  toInt8OrDefault
- [ ]  toInt8OrNull
- [ ]  toInt8OrZero
- [ ]  toIntervalDay
- [ ]  toIntervalHour
- [ ]  toIntervalMicrosecond
- [ ]  toIntervalMillisecond
- [ ]  toIntervalMinute
- [ ]  toIntervalMonth
- [ ]  toIntervalNanosecond
- [ ]  toIntervalQuarter
- [ ]  toIntervalSecond
- [ ]  toIntervalWeek
- [ ]  toIntervalYear
- [ ]  toRelativeDayNum
- [ ]  toRelativeHourNum
- [ ]  toRelativeMinuteNum
- [ ]  toRelativeMonthNum
- [ ]  toRelativeQuarterNum
- [ ]  toRelativeSecondNum
- [ ]  toRelativeWeekNum
- [ ]  toRelativeYearNum
- [X]  toStartOfMicrosecond
- [X]  toStartOfMillisecond
- [X]  toStartOfNanosecond
- [ ]  toTime
- [ ]  toTimezone
- [ ]  toTypeName
- [ ]  toUInt128
- [ ]  toUInt128OrNull
- [ ]  toUInt128OrZero
- [ ]  toUInt16
- [ ]  toUInt16OrDefault
- [ ]  toUInt16OrNull
- [ ]  toUInt16OrZero
- [ ]  toUInt256
- [ ]  toUInt256OrDefault
- [ ]  toUInt256OrNull
- [ ]  toUInt256OrZero
- [ ]  toUInt32
- [ ]  toUInt32OrDefault
- [ ]  toUInt32OrNull
- [ ]  toUInt32OrZero
- [ ]  toUInt64
- [ ]  toUInt64OrDefault
- [ ]  toUInt64OrNull
- [ ]  toUInt64OrZero
- [ ]  toUInt8
- [ ]  toUInt8OrDefault
- [ ]  toUInt8OrNull
- [ ]  toUInt8OrZero
- [ ]  toUnixTimestamp64Micro
- [ ]  toUnixTimestamp64Milli

**Comment by Blargian** [comment]
@rschu1ze In the docs for type conversion functions we have [toUInt(8|16|32|64|256)](http://localhost:3000/docs/en/sql-reference/functions/type-conversion-functions#touint8163264256), [toUInt(8|16|32|64|256)](https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#touint8163264256) and other variants where all the functions are grouped together. We also have [reinterpretAs(U)Int*](https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#reinterpretasuint8) functions which are not grouped but rather listed individually : `reInterpretUInt8`, `reInterpretUInt16`, `reInterpretUInt32`... etc. 

Should I split up the grouped functions to individual listings? 

On the one hand it makes the `Type Conversion Functions` more verbose as there is a lot of copy-pasted information, but on the other hand I think this is maybe not the worst thing for documentation. In my opinion it looks neater, makes it easier to find what you are looking for and makes the docs more complete if there are examples for each function rather than just one generic example for each group. 

I gather that there are differing opinions on this between the docs team and the core team based on the discussion [here](https://github.com/ClickHouse/ClickHouse/pull/59392#discussion_r1494703991).

**Comment by rschu1ze** [comment]
@Blargian That is one of the questions where one can ask 10 people and get 10 different answers :-) My personal opinion is that we should not group 8|16|32|64|128|256 functions but list them individually BUT still try to create a strong cohesion by linking related functions in the "See also" sub-section. For example, `toUInt16` could be linked
- to `toUInt16OrNull`, `toUInt16OrDefault`, `toUInt16OrZero` (which covers all `Or*` function variants)
- to `toUInt8`, `toUInt32`, `toUInt64`, `toUInt128`, toUInt256` (which covers the other data types)

**Comment by Blargian** [comment]
@rschu1ze I'm working now on documenting `toRelative*Num` functions and finding these a little strange. According to the current documentation these functions convert a date or date with time to the number of years, months, days etc from a fixed reference point in time. This is, at least from what I can see for types:

- `Date`, `DateTime` : `1970-01-01`
- `DateTime64` : `1900-01-01`

Based on this:
```sql
SELECT toRelativeYearNum(toDate('1969-01-01'));
SELECT toRelativeYearNum(toDateTime('1969-01-01'));
SELECT toRelativeYearNum(toDateTime64('1899-01-01',6));

1970
1970
1900
```

However the behaviour is not as expected. See for instance [this](https://fiddle.clickhouse.com/6b14e501-bbb6-45a0-840c-f419faf8cee3)

```sql
SELECT toRelativeYearNum(toDate('1969-01-01'));
SELECT toRelativeYearNum(toDate('1970-02-01'));
SELECT toRelativeMonthNum(toDate('1970-02-01'));
SELECT toRelativeDayNum(toDate('1970-02-01'));

1970
1970
23642
31
```

I would expect rather

```response
1970
1970
1
31
```

`SELECT toRelativeYearNum(toDate('2024-01-01'));` also unexpected - returns `2024` and not `54`?

**Comment by rschu1ze** [comment]
Current docs say that `toRelative*` functions `[...], starting from a certain fixed point in the past.`, they don't specify the exact starting point. And this is intentionally so, the purpose of the `toRelative*` functions is not to calculate the distance (in years, quarters, ..., seconds) of a single date or date with time to the starting point (for that purpose, users can simply subtract two dates), but to "normalize" two dates or dates with time relative to the same starting point such that their normalized differences can be compared.

In the reworked docs, we should keep the exact starting point for each function unspecified to give the database some leeway to change it in future.

Oh, in case you wonder, `SELECT toRelativeMonthNum(toDate('1970-02-01'));` is `23642` because "month" is calculated relative to 0000-00-00 00:00:00.
