### ISSUE TITLE
unable to open documentation for minio support

### ISSUE THREAD

**Issue by anjievana** [ClickHouse/clickhouse-docs#2082]

**Comment by johnnymatthews** [comment]
I'm not quite sure what you mean by the title @anjievana. Can you elaborate?

**Comment by anjievana** [comment]
1. Click on this page
https://clickhouse.com/docs/en/integrations
2. Go to `MinIO` and click on 'documentation'

Then the page is broken and giving following 
```
Ruh-roh! We can't find that page. 😬
If this page should exist, [please open a Github issue](https://github.com/ClickHouse/clickhouse-docs/issues) and let us know a link is broken.
```

**Comment by johnnymatthews** [comment]
I think you've found an interesting bug. If you just click on that link, you get the 404 _can't find this page_ page, as you mentioned. But if you open that link in a new tab, it takes you to the correct page: https://clickhouse.com/docs/en/integrations/s3/s3-minio

This might be due to a funky/broken redirect we have in place. I'll take a look. Thanks for flagging!

**Comment by johnnymatthews** [comment]
Update the link in #2090. Should be fixed now.
