### ISSUE TITLE
When I type "create user" it cannot find a page named "create user"

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#296]
It's not in the search suggest.

![Screenshot_20220815_032213](https://user-images.githubusercontent.com/18581488/184667384-c4470202-1ea0-4bc9-876a-b79027b8e4fd.png)

**Comment by DanRoscigno** [comment]
working in this now.  The category (folder) is named create, and this level (lvl0) gets the highest precedence.  I am seeing how I can assign lvl0 at the individual page level... `tags` looks like it should work, we will see in an hour.

**Comment by DanRoscigno** [comment]
tags did not work, I asked in the docusaurus discord.

**Comment by DanRoscigno** [comment]
Algolia has said that because of our deep doc structure we need to customize the configuration of the crawler.  I have done some configuration already to raise the priority of doc pages vs. changelog (so that settings in the settings pages are above settings in the changelogs) and will have a look at fixing this in a while.

**Comment by DanRoscigno** [comment]
Better:
![image](https://user-images.githubusercontent.com/25182304/185806368-84b72646-2ebd-411e-a2c6-00633dd70698.png)
